### ISSUE TITLE
feat: Add the ability to write a text review of the candidate instead of just numbers.

### ISSUE THREAD

**Issue by mohamedAdhamc** [Deadreyo/SemiColon-dashboard-frontend#29]
## Is your feature request related to a problem? Please describe.

Add the ability to write a text review of the candidate instead of just numbers.

## Additional context

only numbers as of now.

**Comment by Deadreyo** [comment]
@mohamedAdhamc it is present
![image](https://github.com/Deadreyo/SemiColon-dashboard-frontend/assets/52013393/4470bb0f-204f-44b0-9639-df0bcf734dd9)
